apiVersion: v1
kind: Service
metadata:
  name: category-service
  labels:
    app: newsnest
    component: category-service
spec:
  type: ClusterIP
  selector:
    app: newsnest
    component: category-service
  ports:
    - port: 4002
      targetPort: 4002
      protocol: TCP
