apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: newsnest
    component: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: newsnest
      component: api-gateway
  template:
    metadata:
      labels:
        app: newsnest
        component: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: shivam985/newsnest-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: newsnest-config
                  key: NODE_ENV
            - name: API_VERSION
              valueFrom:
                configMapKeyRef:
                  name: newsnest-config
                  key: API_VERSION
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: newsnest-config
                  key: ALLOWED_ORIGINS_GATEWAY
            - name: NEWS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: newsnest-config
                  key: NEWS_SERVICE_URL
            - name: CATEGORY_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: newsnest-config
                  key: CATEGORY_SERVICE_URL
          resources:
            requests:
              cpu: "100m"
              memory: "96Mi"
            limits:
              cpu: "300m"
              memory: "192Mi"
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
